export const types = [
  { type: "ground", color: "#967b4f" },
  { type: "fire", color: "#ff5733" },
  { type: "water", color: "#1e90ff" },
  { type: "dragon", color: "#7e1f9e" },
  { type: "grass", color: "#2ecc71" },
  { type: "electric", color: "#f1c40f" },
  { type: "dark", color: "#34495e" },
  { type: "flying", color: "#87ceeb" },
  { type: "normal", color: "#A8A77A" },
  { type: "fighting", color: "#C22E28" },
  { type: "poison", color: "#A33EA1" },
  { type: "rock", color: "#B6A136" },
  { type: "ghost", color: "#735797" },
  { type: "steel", color: "#B7B7CE" },
  { type: "ice", color: "#98D8D8" },
  { type: "psychic", color: "#F95587" },
  { type: "bug", color: "#A6B91A" },
  { type: "fairy", color: "#EE99AC" },
];
